version: '3.8'

services:
  server:
    build:
      context: .
    restart: unless-stopped
    container_name: "spring-cloud-config"
    volumes:
      - ./config:/config
    ports:
      - "8080:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - SPRING_PROFILES_INCLUDE=native
